name: Add Issue Description

on:
  issues:
    types: [opened]

jobs:
  add_description:
    runs-on: ubuntu-latest
    steps:
      - name: Read issue template
        id: read_template
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            return fs.readFileSync('./templates/Issue-template.md', 'utf8');

      - name: Set issue description
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const description = context.payload.issue.body + "\n\n---\n\n" + ${{ steps.read_template.outputs.result }};
            await github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: description
            });
